export const course_name = {
	IGNOU: [
		'MES-012: Education: Nature and Purpose',
		'MES-016: Educational Research',
		'BES-121:Childhood and Growing Up',
		'BES-122: Contemporary India and Education',
		'BES-123: Learning and Teaching',
		'BES-124:Language Across the Curriculum',
		'BES-125:Understanding Disciplines and Subjects',
		'MDE-411: Growth and Philosophy of Distance Education',
		'MDE-413: Learner Support Systems and Services',
		'MDE-414: Management of Distance Education',
		'MDE-415: Research for Distance Education',
		'MDE-416: Curriculum Development for Distance Education',
		'MDE-417: Distance Education: Economic Perspective',
		'MEVE-019: Environmental Issues',
		'MDE-419: Staff Training and Development in Distance Education',
		'MDI-001: Migration and Diaspora: Theory and Methodology',
		'BPYI-101: Applied Ethics',
		'BPCC-131: Foundations of Psychology',
		'BSOC -107: Sociology of Gender',
		'BHIS-183: Traditions and perceptions of crafts in Bharat',
		'BANC 131 Anthropology and Research Methods',
		'BANC 102 Introduction to Social and Cultural Anthropology',
		'MCS-211 Design and Analysis of Algorithms',
		'MCS-212 Discrete Mathematics Theory',
		'BCS-011 Computer Basics and PC Software',
		'BCS-012 Basic Mathematics',
		'MLI-101 : Information, Communication and Society',
		'Introduction to the Legal System',
		'MJM-024: Media and Society',
		'BTME-141: Tourism Undertaking',
		'BTME-143: Procedure and Operations in the Tourism Business',
		'BFO-015: Managing Facilities-II',
		'BTMG-171: Culture in Indian Subcontinent- 1',
		'BTMS-185: Airport Handling',
		'MMPC-001: Management Functions and Organizational Processes',
		'MMPC-002: Human Resource Management',
		'MMPC-003: Business Environment',
		'MMPC-004: Accounting for Managers',
		'MMPC-005: Quantitative Analysis for Managerial Applications',
		'MMPC-006: Marketing Management',
		'MMPC-007: Business Communication',
		'MMPC-008: Information Systems for Managers',
		'MMPC-009:Management of Machines and Materials',
		'MMPC-010: Managerial Economics',
		'MMPC-011: Social Processes and Behavioural Issues',
		'MMPC-012: Strategic Management',
		'MMPC-013: Business Law',
		'MMPC-014: Financial Management',
		'BRL-101: Overview of Retailing',
		'BRL-102: Introduction to Retail Marketing',
		'BRL-103: Store Operations',
		'BRL-104: Retail Management Perspectives and Communication',
		'BRL-105: Computer Service Management',
		'BRL-106: Managing Human Resources',
		'BRL-107: Buying and Merchandising-1',
		'BRL-108: Retail Operations and Store Management',
		'BRL-109: Customer Value Management',
		'BRL-110: IT Application in Retail',
		'BCOS-186: Personal Selling and Salesmanship',
		'BCOE-142: Management Accounting',
		'BCOS-185: Entrepreneurship',
		'BCOC-137: Corporate Accounting',
		'BCOC-135: Company Law',
		'BCOC-138: Cost Accounting',
		'BZYET-141: Immunology',
		'MMPM006 Marketing Research',
		'Basics of Apparel Industry and Entrepreneurship BHC005',
		'Digital Pedagogy and Learning Design',
		'MOOCs and OER',
		'Research/ICT in Research',
		'Disability and Education',
		'E-Content Design and Development',
		'Governance and Leadership in HE',
		'Assessment and Evaluation in HE',
		'Soft Skills for Teachers',
		'Multi-Disciplinary Course Design and Development',
		'Online Learning: Design, Development and Delivery',
		'MHD-10 ेमचंद कहानी िविवधा',
		'BHDS -183 अनुवाद िस ांत और िविध (वैक क)',
		'BHDS -184 रे िडयो लेखन (वैक क)',
		'MUD-002 Urdu Ghazal',
		'MUD-008 Classiki Urdu Shairi',
		'BUDC-104- Jadeed Urdu Ghazal Ka Mutala',
		'BEGAE 182 : English Communication Skills',
		'BEGLA :138 Reading and Speaking Skills',
		'BEGC 111: Women Writing',
		'BSKAE 181 Indian Knowledge System',
		'MSK 005 Vadik Vagmaya Evam Bhartiya Sanskrit Aur Sabhyata',
		'MJY-002 िस ा ोितष एवं काल',
		'MHN-001 िह दू अ यन की अवधारणा एवं प',
		'MVS-003 वैिदक गिणत एवं सृि िव ान',
		'Principles of Political Science (BPSS-11)',
		'An Introduction to Criminology and Criminal Justice Administration (MCCJ-11)',
		'Processes of Geomorphology (MGEOS-11)',
		'Introduction to Business Studies- BBA(N) 201',
		'Differential Equation-MT(N)102',
		'Python Programming - MCS-E2',
		'Fundamentals of Research and Data Analysis Techniques- MCM-502',
		'िस ा ोितष एवं काल िववेचन - MAJY-502/506',
		'Pilgrimage Tourism in India BTTM (N) 503',
		'Panchang evam Muhurat MAJY-503',
		'BBCET151: Plant Biochemistry',
		'BBCCT-103: Cell Biology',
		'BBCCT-109: Metabolism of Carbohydrates and Lipids',
		'MVP 001: Food Fundamentals and Chemistry',
		'BGYCT-135: Petrology',
		'BHC-006 Fashion, Textiles, Product Development and Merchandising',
		'Political Theory (Part A) UG PS S1-01 (DSC/DSE)',
		'Business Organization and Business Ethics UG CM S1- 01 (DSC/DSE)',
		'Concept of Communication',
		'Cyber Security',
		'Open Source Software for Skill Development',
		'History of Economic Thought',
		'Social Work in Persons with Disability PGMSW 04',
		'Sociology of Northeast India UGSOS404',
		'Introduction to Sociology UGSOS101',
		'Agricultural Economics UGECOS510',
		'Social and Political Philosophy UGPHIS603',
		'An Introduction to Assam History UGHTS201',
		'Business Organization and Business Ethics DSC1/DSE1',
		'Indian Financial System DSC4',
		'Financial Market and Services PGCM(S4)2',
		'Management Process and Organizational Behaviour PGBA(S1)1',
		'Human Resource Management PGBA(S2)1',
		'History of Assamese Literature, Script and Inscription (From Beginning to Post-SankardevaPeriod) UG AS S1-01 (DSC/DSE)',
		'Indian Knowledge System UG IKS',
		'Concept of Communication, PG JMC S1 01',
		'Distance Education, GED S 04',
		'Political Science',
		'BPCC-102: Biopsychology',
		'Course-I: Political Theory: Key Concepts',
		'BRL-101: Overview of Retailing 20',
		'BRL-103: Store Operations 20',
		'Financial Accounting (CC-CO-01)',
		'Cost Accounting (CC-CO-O3)',
		'Direct Taxation (CC-CO-08)',
		'Financial Management (DS-CO-41)',
		'Taxation (Paper-5)',
		'Corporate Tax Planning (Paper-16)',
		'Computer Basics and Applications in Library and Information Science) (Paper-8)',
		'Knowledge Organisation (Cataloguing) (Paper-4)',
		'Information Sources, Systems and Services (Paper-2)',
		'Digital Information Search and Retrieval (Paper-3)',
		'Yoga Education (VAC-3)',
		'Introduction to Educational Studies (CC-ED-01)',
		'Education and Community Development (DS ED 41)',
		'Sociological Foundation of Education  Module - 1: Education and Society (PGED-III)',
		'Educational Technology and Curriculum Studies  Module – 1: Educational Technology (PGED-V)',
		'Library Classification Theory (Paper 3)',
		'Library Classification (Practice) (Paper 6)',
		'Information, Communication and Society (Paper 1)',
		'Research Methodology (Paper 7)',
		'Application of Social Work in Social Milieu (Paper-15)',
		'Management of Library and Information Centre (Paper 5)',
		'Information Technology: Applications (Paper 6)',
		'other'
	],

	'IIT Bombay': [
		'Physical Chemistry',
		'Genetic Engineering',
		'Biomolecular Spectroscopy',
		'Microbiology',
		'Fluid Dynamics',
		'Innovation and Creativity',
		'Introductory Satellite Image Processing',
		'Micro Nano Photonics',
		'Embeded systems',
		'Speech Processing',
		'Intelligent Feedback and Control',
		'Linear Algebra-1',
		'Electromagnetic waves',
		'Digital Protection of Power Systems',
		'Sustainable energy storage systems',
		'Control of Nonlinear Dynamical Systems',
		'Linear Control Systems: A state-space approach',
		'Indian Economic and Business Models',
		'Introduction to Quantum Physics',
		'Photonics',
		'Analytical Methods in Physics',
		'Introduction to Concepts and Experimental Methods in Soft Matter',
		'Quantum Mechanics II',
		'Introduction to Air Transportation',
		'Transportation Engineering',
		'other'
	],
	'IIT Delhi': [
		'Evaluation of Textiles – The Analytical Approaches',
		'Theory of Structures and Mechanics of Textile Materials',
		'Statistics for Textile and Apparel Engineers',
		'Introduction to Healthcare Engineering',
		'other'
	],

	'IIT Gandhinagar': [
		'Infrastructure Systems: Decision, Risk, and Resilience',
		'Video Production for Educational Television',
		'Analysis and Design of Rigid Pavements',
		'Fundamentals of Air Quality',
		'Fundamentals of Neuroscience',
		'Networks & Complex Systems',
		'other'
	],

	CEC: ['course name', 'other'],

	'IIT Kanpur': [
		'Reading Ambedkar (Hindi)',
		'Modern India (1757-1857)',
		'Bivariate Descriptive Statistics (Hindi)',
		'Probability and Probability Distributions (Hindi)',
		'Mathematical Analysis',
		'Ethics: Indian and Western (नीतिशास्त्र: भारिीयएवं पाश्चात्यदाशशतनकतिद्ांि)',
		'Agronomy Of Oilseed, Fibre And Sugar Crops',
		'Public Policy, Decentralization and Administration in India (Hindi)',
		'Public International Law',
		'Administrative Law',
		'Indian Evidence Act, 1872',
		'आपरातिक तवति II ( दंड प्रतकया िंतििा ) Cr.P.C',
		'Human Rights and Criminal Justice System',
		'Principles of Management',
		'Product design - II',
		'Policing: Law and Practice (Hindi)',
		'THE WTO LAW AND INTERNATIONAL TRADE',
		'Product design - I',
		'Corporate Strategic Management',
		'MANAGING EQUALITY AND DIVERSITY',
		'Organizational Excellence: Change & Development (Hindi)',
		'Signages and Wayfinding',
		'Law of Banking and Negotiable Instruments',
		'Foundations of Psychological Processes (Hindi)',
		'Experimental Methodology & Elementary Statistics (Hindi)',
		'Labour and Industrial Laws- I (Hindi)',
		'Philosophy of Architecture or Mind of Architecture',
		'संवैधानिक विधि',
		'Design for the Real world : A Problembased Learning Approach',
		'िंपति अंिरण अतितनयम, 1882 ( The Transfer of Property Act, 1882)',
		'Thermodynamics and Thermal Engineering',
		'Intellectual Property Laws',
		'Introduction to International Relations: Concept and Issues',
		'Constitutional Law',
		'Law Relating to Women and Children',
		'Professional Ethics (Legal Ethics)',
		'Intellectual Property Rights',
		'Human Resource Management',
		'Labour and Industrial Laws- II (Hindi)',
		'General Sociology: Key Concepts',
		'Drafting Pleading and Conveyancing',
		'Management of Training and Development',
		'Business Communication',
		'Appreciating and Writing Popular Non-Fiction Books',
		'Natural dyes and Innovative Natural dyeing',
		'Psychology of Human Development',
		'Behavioural Disorders',
		'Stress and coping',
		'International Law and Human Rights',
		'Criminal Law (Bharatiya Nyaya Sanhita, 2023) English',
		'Gender Justice and Feminist Jurisprudence',
		'Juvenile Justice',
		'Feminist Theories: Approaches and Concepts',
		'Financial Market Regulations',
		'Criminology, Penology and Victimology',
		'Law relating to Evidence/ Bharatiya Sakshay Adhiniyam (Hindi)',
		'Bharatiya Jurisprudence (Hindi)',
		'Civil Procedure Code and Limitation Act तितवल प्रतिया िंतििा िथा पररिीमा तवति (Hindi)',
		'Administrative Law प्रशाितनक तवति (Hindi)',
		'Insurance Law (English)',
		'बीमा तवति (Hindi)',
		'Maritime Law (English)',
		'Muslim Law (Hindi)',
		'Competition Laws (Hindi)',
		'Cyber Crimes (English)',
		'Cyber Crimes (Hindi)',
		'Law of Contract (Hindi)',
		'Law of Contract (English)',
		'White Collar Crimes',
		'The Transfer of Property Act',
		'Company Law (Hindi)',
		'Environmental Laws',
		'अपकृ त्य तवति और उपभोक्ता िंरक्षण अतितनयम, 2019',
		'Law, Science & Technology',
		'Interpretation of Statues',
		'Socio-Economic Offences in India',
		'Land Laws',
		'Labour and Industrial Law I',
		'Labour Law II',
		'Hindu Law (Hindi)',
		'Hindu Law (English)',
		'Competition Law',
		'Corporate Governance',
		'Corporate Finance',
		'Family Law (Hindu Law)',
		'Legal Research Methods and Methodology',
		'Minor Acts (The Court Fees Act 1870, The Suits Valuation Act, 1887, Indian Stamp Act, 1899, The Registration Act, 1908, The Advocates Act, 1961, The Contempt of Courts Act, 1971)',
		'Multivariate Data Mining- Methods and Applications',
		'Principles of Taxation Law',
		'CALCULUS-II',
		'Option Pricing: A Mathematical view',
		'other'
	],
	'IIT Kharagpur': ['Working Drawing', 'Basics of Building Construction', 'other'],

	'IIT Tirupati': [
		'Solid State (structural aspects)',
		'Quantum Chemistry and Chemical Bonding in Bengali',
		'Chemical Kinetics in Bengali Language',
		'Inorganic Reaction Kinetics in Bengali',
		'Chemical Thermodynamics',
		'Stereochemistry and Reaction Mechanism',
		'Coordination Chemistry in Bengali',
		'Complex Analysis in Tamil Language',
		'Linear Algebra in Tamil langauge',
		'Functional Analysis in Tamil Language',
		'other'
	],

	'University of Hyderabad': [
		'Ragas of South Indian Music',
		'Dikshita Kriti Manimala',
		'Pallavi and its Special Features',
		"Varnam' - Practical applications and Theoretical Perspectives",
		'Kamalamba Navavarana Kritis of Muthuswamy Dikshitar',
		'The Compositions of Swati Tirunal',
		'Compositions of Mysore Composers',
		'Musical References in Sanskrit Texts',
		"Rare Varnams' and the varied Dimensions",
		'Konnakkol - Indian Traditional Vocal Percussion',
		'Voxology and Voice Culture',
		"Andhra 'Dasa' Sampradaya Keertanalu",
		'Sitar and Raga Elaboration - Level 1',
		'Ekaika Raga Kritis of Thyagaraja',
		'Compositions of Modern Composers',
		'Veena Mastery: From Fundamentals to Advanced Techniques.',
		'Guruguha Vibhakti Kritis of Muthuswamy Dikshitar',
		'Learning Carnatic Violin: Techniques and skills',
		'Overview of Musical Treatises',
		'Playing Sitar: Techniques for Beginners',
		"Fundamental Techniques and skills for Playing 'Esraj' instrument",
		'Sri Thyagaraja Kirtana Manjari',
		'Abhyasa Ganam - Level 2',
		'Intro to Video Production',
		'other'
	],

	'IIT Madras': [
		'Anatomy',
		'Microbiology',
		'Biochemistry',
		'Pathology',
		'Research Science Initiatives',
		'Introduction to Spectroscopy',
		'Problem Solving',
		'Basics to advanced electrochemistry related to energy storage and conversion systems',
		'Socio-historical aspects of medicine',
		'Introduction to Topology',
		'Classical Differential Geometry of Curves and Surfaces',
		'Untitled',
		'Software Enginnering',
		'Environmental Science',
		'Mechanics of Bodies',
		'Wireless and Cellular Communication systems',
		'Sanga Illakiyam Purananuru ( Tamil)',
		'Untitled',
		'Solid State (structural aspects)',
		'Quantum Chemistry and Chemical Bonding in Bengali',
		'Mathematical Foundation of AI & MI',
		'Corrosion',
		'Probability and Stochastic Processes',
		'Ordinary Differential Equations (ODE)',
		'other'
	]
};
