export const discipline = [
	'Aerospace Engineering',
	'Agricultural and Food Engineering',
	'Applied Geology',
	'Applied Geophysics',
	'Applied Mathematics and Scientific Computing',
	'Applied Mechanics',
	'Architecture and Planning',
	'Architecture, Planning &amp;amp; Design',
	'Artificial Intelligence &amp; Data Science',
	'Astronomy, Astrophysics and Space Engineering',
	'Biochemical Engineering and Biotechnology',
	'Biological Engineering',
	'Biological Sciences &amp;amp; Bioengineering',
	'Biomedical Engineering',
	'Biosciences and Biomedical Engineering',
	'Biotechnology',
	'Ceramic Engineering',
	'Chemical and Biochemical Engineering',
	'Chemical and Material Sciences',
	'Chemical Engineering',
	'Chemical Sciences',
	'Chemistry',
	'Chemistry and Chemical Biology',
	'Civil &amp;amp; Environmental Engineering',
	'Civil &amp;amp; Infrastructure Engineering',
	'Civil and Environmental Engineering',
	'Civil Engineering',
	'Climate Change',
	'Cognitive Science',
	'Computer Science and Engineering',
	'Computing and Electrical Engineering',
	'Data Science',
	'Design',
	'Earth Sciences',
	'Earthquake Engineering',
	'Economic Sciences',
	'Economics',
	'Electrical Engineering',
	'Electrical Sciences',
	'Electronic Engineering',
	'Electronics &amp;amp; Electrical Engineering',
	'Electronics and Communication Engineering',
	'Energy Science and Engineering',
	'Engineering Design',
	'Engineering Science',
	'Environmental Science and Engineering',
	'Fuel, Minarals and Mettalurgical Engineering',
	'Heritage Science and Technology',
	'Humanities &amp;amp; Social Sciences',
	'Hydro and Renewable Energy',
	'Industrial &amp;amp; Management Engineering',
	'Liberal Arts',
	'Management Studies',
	'Materials Science and Metallurgical Engineering',
	'Mathematics',
	'Mathematics &amp;amp; Computing',
	'Mathematics &amp;amp; Statistics',
	'Mechanical Engineering',
	'Mining Engineering',
	'Nuclear Engineering &amp;amp; Technology',
	'Ocean Engineering',
	'Paper Technology',
	'Petroleum Engineering',
	'Photonics Science and Engineering Programme',
	'Pharmaceutical Engineering',
	'Physical Sciences',
	'Physics',
	'Polymer and Process Engineering',
	'Space Science and Astronomy',
	'Sustainable Energy Engineering',
	'Textile and Fibre Engineering',
	'other'
];
